# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  sad-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: sad-mysql
    volumes:
      - sad-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sad
      - MYSQL_DATABASE=sad
      - MYSQL_USER=sad
      - MYSQL_PASSWORD=sad
  
  # PHPMyAdmin
  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   links:
     - mysql
   environment: 
      PMA_HOST: mysql
      PMA_PORT: 3306
   ports:
     - "8181:81"

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: sad-app
    volumes:
      - .:/var/www/app
    ports:
      - "81:8181"
    links:
      - mysql
  
  